version: '3.7'
services:
  # Service and dependencies
  # ------------------------
  app:
    build:
      context: .
      target: service
    restart: always
    ports:
      - 3001:3000

  # Tests
  # -----
  integration:
    build:
      context: .
      target: test
    depends_on:
      - app
    command: npm run test:integration
    environment:
      - APP_HOST=http://app:3000
